name: Documentation

on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/docs.yml'
      - 'content/**'
  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/docs.yml'
      - 'content/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jdknight/docs-support-container:latest

    steps:
    - name: Checkout releng-tool
      uses: actions/checkout@v4
      with:
        repository: releng-tool/releng-tool
        path: releng-tool

    - name: Checkout releng-tool-docs
      uses: actions/checkout@v4
      with:
        repository: releng-tool/releng-tool-docs
        path: releng-tool-docs

    - name: HTML
      run: ./build html
      working-directory: releng-tool-docs/content

    - name: PDF
      run: ./build latexpdf
      working-directory: releng-tool-docs/content

    - name: Archive generated PDF
      uses: actions/upload-artifact@v4
      with:
        name: releng-tool.pdf
        path: releng-tool-docs/content/_build/latex/releng-tool.pdf
