name: Draft publish

on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/draft-publish.yml'
      - 'content/**'
      - 'locale/**'
      - 'www/**'
  workflow_dispatch:

jobs:
  development-doc-update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jdknight/docs-support-container:latest

    steps:
    - name: Checkout releng-tool
      uses: actions/checkout@v4
      with:
        repository: releng-tool/releng-tool
        path: releng-tool

    - name: Checkout releng-tool-docs
      uses: actions/checkout@v4
      with:
        repository: releng-tool/releng-tool-docs
        path: releng-tool-docs

    - name: Checkout releng-tool-www-docs-develop
      uses: actions/checkout@v4
      with:
        repository: releng-tool/releng-tool-www-docs-develop
        path: releng-tool-www-docs-develop
        ssh-key: ${{ secrets.WWW_DOCS_DEVELOP_AUTOPUBLISH }}

    - name: Update translations
      run: |
        cd releng-tool-docs/locale
        ./update

    - name: Build documentation
      run: |
        cd releng-tool-docs/www
        ./generate --domain docs-develop.releng.io

    - name: Moving over new development translations
      run: |
        rsync --exclude='.git/' --archive --delete --verbose \
            $GITHUB_WORKSPACE/releng-tool-docs/www/_build/ \
            $GITHUB_WORKSPACE/releng-tool-www-docs-develop/

    - name: Publish development changes
      run: |
        cd releng-tool-www-docs-develop
        git config --global user.name 'releng-tool bot'
        git config --global user.email 'noreply@releng.io'
        git add .
        if git commit -am "automated development update"; then
          git push origin main
        fi
